// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmLPemArlIMPtg3Ia3achXPE8S9RJX5Qs',
    appId: '1:1044430954378:android:38b4a2695ae47191143273',
    messagingSenderId: '1044430954378',
    projectId: 'kartikey-cyber-security',
    storageBucket: 'kartikey-cyber-security.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVrB9dmE59n6ikT4zcjh814ai9qzjJfP8',
    appId: '1:1044430954378:ios:f9b248b60f6828ed143273',
    messagingSenderId: '1044430954378',
    projectId: 'kartikey-cyber-security',
    storageBucket: 'kartikey-cyber-security.appspot.com',
    androidClientId: '1044430954378-dccs7s3c3h6fsg5ckg2mlece3h8uqibf.apps.googleusercontent.com',
    iosClientId: '1044430954378-15u70drl1n8kilg8covt8c5vf0mmnt9s.apps.googleusercontent.com',
    iosBundleId: 'com.kartikeyraghav.cyborg',
  );
}
